FROM docker.io/bitnami/spark:2.4.5
# docker.io/bitnami/spark:2.4.5 -> spark 2.4.5, python 3.6.10, scala 2.11.12, https://github.com/bitnami/bitnami-docker-spark, https://hub.docker.com/r/bitnami/spark
# LEGACY CODE.
USER root


# Pip installs. Using local copy to tmp dir to allow checkpointing this step (no re-installs as long as requirements_base_alt.txt doesn't change)
COPY yaetos/scripts/requirements_base_alt.txt /tmp/requirements.txt
WORKDIR /tmp/
RUN apt-get update && apt-get install -y git
RUN pip3 install -r requirements.txt
RUN apt install nodejs -y

WORKDIR /mnt/yaetos

ENV YAETOS_FRAMEWORK_HOME /mnt/yaetos/
ENV PYTHONPATH $YAETOS_FRAMEWORK_HOME:$PYTHONPATH
# ENV SPARK_HOME /usr/local/spark # already set in base docker image
ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/build:$PYTHONPATH

ENV YAETOS_JOBS_HOME /mnt/yaetos_jobs/
ENV PYTHONPATH $YAETOS_JOBS_HOME:$PYTHONPATH

# Expose ports for monitoring.
# SparkContext web UI on 4040 -- only available for the duration of the application.
# Spark master’s web UI on 8080.
# Spark worker web UI on 8081.
# Jupyter web UI on 8888.
EXPOSE 4040 8080 8081 8888

# CMD ["/bin/bash"] # commented so the command can be sent by docker run

# Usage: docker run -it -p 4040:4040 -p 8080:8080 -p 8081:8081 -v ~/code/yaetos:/mnt/yaetos -v ~/.aws:/root/.aws -h spark <image_id>
# or update launch_env.sh and execute it.
